version: 2.1

jobs:
  build_doc_r:
    machine:
      image: ubuntu-2004:202111-01

    steps:
      - checkout
      - run:
          name: Build documentation
          working_directory: docs
          command: |
            ./build-rdoc.sh
            if [ -n "$(git status --porcelain)" ]; then
              exit 1
            fi

  build_doc:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update --yes
            sudo apt-get install default-jdk --yes
            sudo apt-get install maven --yes
            java -version
      - run:
          name: Install Python dependencies
          command: |
            pip --version
            pip install --progress-bar off -r requirements/doc-requirements.txt pytest pytest-cov plotly .
      - run:
          name: Build documentation
          working_directory: docs
          environment:
            JAVA_HOME: /usr/lib/jvm/default-java
          command: |
            make rsthtml
            make javadocs
      - run:
          name: Test examples
          working_directory: docs
          command: |
            make test-examples
      - store_artifacts:
          path: docs/build/html

  mlflow-recipes:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Pull submodule
          command: |
            git submodule update --init --recursive
      - run:
          name: Install dependencies
          command: |
            pip install -e .
            pip install nbconvert ipykernel
      - run:
          name: Run CLI
          working_directory: examples/recipes/regression
          environment:
            MLFLOW_RECIPES_PROFILE: local
          command: |
            mlflow recipes run
      - run:
          name: Run notebook
          working_directory: examples/recipes/regression
          environment:
            MLFLOW_RECIPES_PROFILE: local
          command: |
            jupyter nbconvert --to html --execute notebooks/jupyter.ipynb
            jupyter nbconvert --to html --execute notebooks/jupyter.ipynb --output dark-jupyter --HTMLExporter.theme=dark

      - store_artifacts:
          path: ~/.mlflow/recipes
      - store_artifacts:
          path: examples/recipes/regression/notebooks/jupyter.html
      - store_artifacts:
          path: examples/recipes/regression/notebooks/dark-jupyter.html

workflows:
  build:
    jobs:
      - build_doc
      - build_doc_r
      - mlflow-recipes
